name: Continuous Deployment

on:
  push:
    branches:
    - main

jobs:
  buildSite:
    name: Update website
    runs-on: ubuntu-latest
    steps:
      - name: Start update
        run: |
          curl -v -X POST \
          -H "Content-Type: application/json" \
          -d '{"secret": "${{ secrets.CD_SECRET}}"}' unito.olinfo.it:23529/main
