name: Deployment previews

on:
  pull_request_target:
    branches:
    - main

jobs:
  buildSite:
    name: Deployment preview 
    runs-on: ubuntu-latest
    steps:
      - name: Build and deploy preview 
        run: |
          curl --fail -v -X POST \
          -H "Content-Type: application/json" \
          -d '{"secret": "${{ secrets.CD_SECRET}}", "sha": "${{ github.event.pull_request.head.sha }}", "gh_token": "${{ secrets.STATUS_ACCESS_TOKEN }}"}' \
          unito.olinfo.it:23529/nightly
